### PR TITLE
Support for case-insensitive checkboxes for render. [x] == [X]

### PR DESCRIPTION
**Pull request by samb0t**
Certain utilities including [vimwiki](https://github.com/vimwiki/vimwiki) generate checkboxes using the capital `[X]`. This change adds support for either x or X within checkboxes.

### CODE REVIEW

**Comment by yaniswang** [comment]
We support task list:

Tasklist:
---------------

	- [x] This task is done
	- [ ] This is still pending

**Comment by yaniswang** [comment]
https://raw.githubusercontent.com/yaniswang/markdownReader/master/README.md

**Comment by yaniswang** [comment]
I know your point, i support you push code to showdownjs first.

https://github.com/showdownjs/showdown

Then update markdownReader.

**Comment by samb0t** [comment]
Will do. Thanks for the quick reply.

**Comment by samb0t** [comment]
As a quick update, this change was pulled into showdown in [this](https://github.com/showdownjs/showdown/commit/77007181d8ebe5aac89236b8b8dd0c6fd4ae0250) change request. I'm just waiting on a new /dist build.

**Comment by samb0t** [comment]
Closing this request. Will open a new request that updates showdown.js to v. 1.4.0. This includes my change.

**Pull request closed without merging**
