### PR TITLE
Updating showdown to version 1.4.0

### PR DESCRIPTION
**Pull request by samb0t**
Per your suggestion, my case-insensitive checkbox has been merged into showdown.js master. This pull request simply updates showdown.js to the latest version.

### CODE REVIEW

**Comment by yaniswang** [comment]
This version test deep?

**Comment by samb0t** [comment]
This version of showdown was copied directly from their [master](https://github.com/showdownjs/showdown/blob/master/dist/showdown.js) branch. They have fairly strict rules surrounding pull requests and require a number of automated builds and tests before merging. I've also tested integration with markdownReader using a a number of complex markdown files and have not seen any incompatibilities. 

Thank you,
Sam

**Comment by samb0t** [comment]
Thanks!

**Comment by yaniswang** [comment]
1.0.12 is released.

**Pull request merged**
